apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: configmap-app
  namespace: argocd
spec:
  project: default
  source:
    # Source 1: Your GitOps repo (for values and ref)
    repoURL: https://github.com/ashutosh-18k92/gitops-v3.git
    targetRevision: HEAD
    path: configmap
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
